services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/code
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_URI=${DB_URI}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./backend/mongo-seed:/mongo-seed
    entrypoint: ["bash", "-c", "chmod +x /mongo-seed/entrypoint.sh /mongo-seed/init-mongo.sh && /mongo-seed/entrypoint.sh"]
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend  # Live-reload in development
      - /frontend/node_modules
    environment:
      - VITE_API_URL=http://app/api
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: